// Generated by gencpp from file assignment1/fusion.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_FUSION_H
#define ASSIGNMENT1_MESSAGE_FUSION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment1
{
template <class ContainerAllocator>
struct fusion_
{
  typedef fusion_<ContainerAllocator> Type;

  fusion_()
    : FusedData()  {
    }
  fusion_(const ContainerAllocator& _alloc)
    : FusedData(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _FusedData_type;
  _FusedData_type FusedData;





  typedef boost::shared_ptr< ::assignment1::fusion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment1::fusion_<ContainerAllocator> const> ConstPtr;

}; // struct fusion_

typedef ::assignment1::fusion_<std::allocator<void> > fusion;

typedef boost::shared_ptr< ::assignment1::fusion > fusionPtr;
typedef boost::shared_ptr< ::assignment1::fusion const> fusionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment1::fusion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment1::fusion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment1::fusion_<ContainerAllocator1> & lhs, const ::assignment1::fusion_<ContainerAllocator2> & rhs)
{
  return lhs.FusedData == rhs.FusedData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment1::fusion_<ContainerAllocator1> & lhs, const ::assignment1::fusion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment1::fusion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment1::fusion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment1::fusion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::fusion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment1::fusion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment1::fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "370f547decfe0b4a69841f116fc2c0fe";
  }

  static const char* value(const ::assignment1::fusion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x370f547decfe0b4aULL;
  static const uint64_t static_value2 = 0x69841f116fc2c0feULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment1::fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment1/fusion";
  }

  static const char* value(const ::assignment1::fusion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment1::fusion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] FusedData\n"
;
  }

  static const char* value(const ::assignment1::fusion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment1::fusion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FusedData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fusion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment1::fusion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment1::fusion_<ContainerAllocator>& v)
  {
    s << indent << "FusedData[]" << std::endl;
    for (size_t i = 0; i < v.FusedData.size(); ++i)
    {
      s << indent << "  FusedData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.FusedData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_FUSION_H
