// Generated by gencpp from file assignment1/Speaker.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT1_MESSAGE_SPEAKER_H
#define ASSIGNMENT1_MESSAGE_SPEAKER_H

#include <ros/service_traits.h>


#include <assignment1/SpeakerRequest.h>
#include <assignment1/SpeakerResponse.h>


namespace assignment1
{

struct Speaker
{

typedef SpeakerRequest Request;
typedef SpeakerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speaker
} // namespace assignment1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment1::Speaker > {
  static const char* value()
  {
    return "8b7095eb8dcd517ba7c37a0a06dcc50b";
  }

  static const char* value(const ::assignment1::Speaker&) { return value(); }
};

template<>
struct DataType< ::assignment1::Speaker > {
  static const char* value()
  {
    return "assignment1/Speaker";
  }

  static const char* value(const ::assignment1::Speaker&) { return value(); }
};


// service_traits::MD5Sum< ::assignment1::SpeakerRequest> should match
// service_traits::MD5Sum< ::assignment1::Speaker >
template<>
struct MD5Sum< ::assignment1::SpeakerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1::Speaker >::value();
  }
  static const char* value(const ::assignment1::SpeakerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1::SpeakerRequest> should match
// service_traits::DataType< ::assignment1::Speaker >
template<>
struct DataType< ::assignment1::SpeakerRequest>
{
  static const char* value()
  {
    return DataType< ::assignment1::Speaker >::value();
  }
  static const char* value(const ::assignment1::SpeakerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment1::SpeakerResponse> should match
// service_traits::MD5Sum< ::assignment1::Speaker >
template<>
struct MD5Sum< ::assignment1::SpeakerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment1::Speaker >::value();
  }
  static const char* value(const ::assignment1::SpeakerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment1::SpeakerResponse> should match
// service_traits::DataType< ::assignment1::Speaker >
template<>
struct DataType< ::assignment1::SpeakerResponse>
{
  static const char* value()
  {
    return DataType< ::assignment1::Speaker >::value();
  }
  static const char* value(const ::assignment1::SpeakerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT1_MESSAGE_SPEAKER_H
